Många ändringar, gå gärna igenom commit för commit.
Dsek-LTH/reglemente pull request #4
Opened 2019-02-04 21:29 UTC by OskarDamkjaer

Mest tveksamma är splittandet av viss att-satser, förenklanden av texter och att jag vill kalla pepparna stabens högra händer istället för högra hand. Roast me

2019-02-04 21:30 UTC, OskarDamkjaer commented
"waow de e inte ok att dela attsatserna eller lägga till valpunkten på karnevalsanvsarig! det får vi lägga som proposition istället!!" - Ni, antagligen

2019-02-06 12:59 UTC, axel-syren reviewed
Lite tveksam om det här med att dela upp att-satserna, även om innebörden inte förändras. Det skulle nog göra sig bättre i en proposition.

Alternativt behåll det som en sats med formuleringen "informera studierådet om kommande Möte<T>, samt om vad som sagts på tidigare Möte<T>"

2019-02-06 13:00 UTC, axel-syren commented on main.tex
> +          \item Ljud- och ljusansvarig
Utmärkt!

2019-02-06 13:18 UTC, axel-syren requested changes
Inkorrekt, se stadgan §21 Ordenssällskapet.

2019-02-06 13:18 UTC, axel-syren commented on main.tex
> +\O verpepparna agerar Nollningsutskottets högra händer genom att vara med i planering
Lite tveksamt om det faktiskt är bättre. Luktar anglicism tycker jag.

2019-02-06 13:24 UTC, axel-syren reviewed
Vad sägs om:

"Överphös Electus sätter ihop en grupp som skall inehålla följande: Överphös Electus själv, minst en gammal stabsmedlem, minst en valberedningsmedlem och en annan valfri person. Gruppen godkänns sedan av styrelsen."

2019-02-08 05:09 UTC, OskarDamkjaer commented
> Vad sägs om:
> 
> "Överphös Electus sätter ihop en grupp som skall inehålla följande: Överphös Electus själv, minst en gammal stabsmedlem, minst en valberedningsmedlem och en annan valfri person. Gruppen godkänns sedan av styrelsen."

Ska hela gruppen väljas av styrelsen?

2019-02-08 05:15 UTC, OskarDamkjaer commented
> Lite tveksam om det här med att dela upp att-satserna, även om innebörden inte förändras. Det skulle nog göra sig bättre i en proposition.
> 
> Alternativt behåll det som en sats med formuleringen "informera studierådet om kommande Möte, samt om vad som sagts på tidigare Möte"

Fixat!

2019-02-10 11:20 UTC, emilwihlander requested changes
Ändra det med nollningsutskottets högra händer så tycker jag det ser bra ut annars!

2019-02-10 11:20 UTC, emilwihlander commented on main.tex
> +\O verpepparna agerar Nollningsutskottets högra händer genom att vara med i planering
Håller med om att det borde vara högra hand.

2019-02-10 13:04 UTC, OskarDamkjaer commented
Såja! Fixat @emilwihlander

2019-02-11 09:14 UTC, emilwihlander approved these changes

2019-02-11 13:48 UTC, merged